name    'coldfront-drupalsi'
version '0.1.0'
source 'https://github.com/coldfrontlabs/drupalsi'
author 'Coldfront Labs Inc.'
license 'GPL License, Version 2.0'
summary 'Drupal site management with Puppet'
description 'Manage Drupal site installations, distributions and installation profiles with Puppet.'
project_page 'https://github.com/coldfrontlabs/drupalsi'

dependency 'coldfront/drush', '>= 0.1.0'