name    'coldfrontlabs-drupalsi'
version '0.2.3'
source 'https://github.com/coldfrontlabs/coldfrontlabs-drupalsi'
author 'Coldfront Labs Inc.'
license 'GPL License, Version 2.0'
summary 'Drupal site management with Puppet'
description 'Manage Drupal site installations, distributions and installation profiles with Puppet.'
project_page 'https://github.com/coldfrontlabs/coldfrontlabs-drupalsi'

dependency 'coldfrontlabs/drush', '>= 0.2.0'
dependency 'puppetlabs/stdlib', '>= 4.4.0'
